title: quiet misdreavus miniblog
name: quiet misdreavus miniblog
description: notes about programming but also whatever else a quiet misdreavus pens down
baseurl: ""
url: "https://quietmisdreavus.net"

exclude: ["README.md"]

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty
